# **Pandas Tutorial**
Pandas is an open source, BSD licensed library providing high-performance, easy to use data structures and data analysis tools for the python programming language

Agenda


*   what is data frames? -- combination of both column and rows and shows a representation format where in how data exactly looks like in the extension in the same it will be loaded
*   what is data series?
*   different operations in pandas

In [ ]:
##first step is to import pandas
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Column4"])
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.to_csv('test1.csv', index=False)

In [ ]:
#accessing the elements
#1. .loc 2. .iloc
#In pandas, .loc and .iloc are used to select specific rows and columns from a DataFrame, but they use entirely different indexing methods.The core difference is that .loc is label-based, while .iloc is integer-position-based.

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [ ]:
type(df.loc['Row1'])

pandas.core.series.Series

In [ ]:
df.iloc[:,:]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
#take elements from column 2 only
df.iloc[:,1:2]

      Column2
Row1        1
Row2        5
Row3        9
Row4       13
Row5       17

In [ ]:
type(df.iloc[:,1:2])

pandas.core.frame.DataFrame

In [ ]:
#converting df into arrays
df.iloc[:, 1:].values.shape

(5, 3)

In [ ]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df['Column1'].value_counts() #.value_counts() function counts the number of times each unique value appears in that specific column.

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [ ]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [ ]:
import kagglehub
path = kagglehub.dataset_download("ensaran/mercedesbenz")

Using Colab cache for faster access to the 'mercedesbenz' dataset.

In [ ]:
import os
print(os.listdir(path))

['train.csv', 'test.csv']

In [ ]:
import os
df=pd.read_csv(os.path.join(path, 'train.csv'))  #csv is comma separated values

In [ ]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [ ]:
df.describe() #only floating value is taken

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000